{
 "title": "HPPT requests",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DNS lookup Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Performance Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\",phase=\"connect\"}\n"
    },
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\",phase=\"resolve\"}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\",phase=\"processing\"}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\",phase=\"tls\"}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\",phase=\"transfer\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:9090\",job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "count(process_cpu_seconds_total)"
    }
   ]
  }
 ]
}